# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'ExchangeRate' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!



  pod 'RxSwift',    '~> 5'
  pod 'RxCocoa',    '~> 5'
  pod 'RxFlow'
  pod 'RxOptional'
  pod 'RxSwiftExt'
  pod 'NSObject+Rx'
  pod 'RxDataSources'
  pod 'Cell+Rx'
  pod 'Action'

  pod 'Then'
  pod 'SnapKit'
  pod 'Reusable'
  #pod 'KeychainSwift'
  
  # Image
  pod 'SDWebImage', '~> 5.0'
#  pod 'lottie-ios'
  pod 'Kingfisher', '~> 5.0'

  # Network
  pod 'Moya/RxSwift',   '~> 14.0'
  
  #Firebase
  pod 'Firebase/Auth'
  pod 'Firebase/Analytics'




  # Pods for ExchangeRate

end
